### ISSUE TITLE
January 13, peer-to-peer code review

### ISSUE THREAD

**Issue by IbrohimRasulov** [gabyse1/to-do-list#3]
## Amazing job 👍  I liked the way of creating functionalities for the app. There are some minor suggestions I can give to make the project more perfect:

  > - [ ] You can simplify your code by making 2 functions into one by changing the event listener type to 'submit'  in order to add a new task.
> - [ ] Also kindly change the live demo link to https://gabyse1.github.io/to-do-list/dist/ in the README.md file, this should work.

### That's all from me, good luck!

<img src="https://media0.giphy.com/media/NEvPzZ8bd1V4Y/giphy.gif"/>

**Comment by gabyse1** [comment]
Hello @IbrohimRasulov.
Thank you for your suggestions. I worked and completed them. 👍
